spec-version: 0.30.0
name: roll
version: 0.1
synopsis: Haskell build tool with fine-grained dependencies
    
github: bergey/roll
author: Daniel Bergey
maintainer: bergey@teallabs.org

library:
    source-dirs: [src]
    ghc-options: "-O2"

executables:
  roll:
    main: roll.hs
    source-dirs:
      - app
    dependencies:
      - roll
      
dependencies:
  - Cabal
  - base >= 4.14.0.0
  - binary
  - containers
  - deepseq
  - directory
  - directory
  - exceptions
  - ghc
  - ghc-paths
  - hashable
  - shake
  - text
  - unix
  - unordered-containers
  - ghc-boot

default-extensions:
  OverloadedStrings
