spec-version: 0.30.0
name: roll
version: 0.1
synopsis: Haskell build tool with fine-grained dependencies
    
github: bergey/roll
author: Daniel Bergey
maintainer: bergey@teallabs.org

library:
    source-dirs: [src]
    ghc-options: "-O2"

executables:
  roll:
    main: roll.hs
    source-dirs:
      - app
    dependencies:
      - roll
      - directory
      - ghc
      - ghc-paths
      - shake
      
dependencies:
  - base >= 4.14.0.0
  - Cabal
  - binary
  - deepseq
  - ghc
  - hashable
  - shake
  - text
  - exceptions
  - containers
  - directory
